name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: mkdir build; cd build; cmake ..
    - name: make
      run: cd build; make
    - name: test
      run: cd build; ./test/test_math_utils
