name: much_stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Stage 1"
  
  stage2:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - run: echo "Stage 2 (depends on Stage 1)"
  
  stage3:
    runs-on: ubuntu-latest
    needs: stage2
    steps:
      - run: echo "Stage 3 (depends on Stage 2)"
