name: much_stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "step1_1!"

    - name: step2
      run: echo "step1_2"
  
  stage2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Stage 2 (depends on Stage 1)"
  
  stage3:
    runs-on: ubuntu-latest
    needs: stage2
    steps:
      - run: echo "Stage 3 (depends on Stage 2)"
