name: much_much_reuse

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "step1_1!"
      
  # 复用外部 workflow
  
  call-reuse-workflow:
    uses: xiaoniuniuniu/hello/.github/workflows/main.yml@main #    指定分支/commit
    permissions:
      contents: read
      actions: read
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
