name: reuse

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "step1_1!"
      
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Stage 2 solid"
  
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo "Stage 3 (depends on Stage 2)"

  call-workflow:
    uses: ./.github/workflows/single_stage.yml
