name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: configure

  build1:
    runs-on: ubuntu-latest
    steps:
    - name: configure1
