name: single_stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "step1_1!"

    - name: step2
      run: echo "step1_2"


  build2:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "step2_1!"

    - name: step2
      run: echo "step2_2"
